development:
  adapter: postgresql
  encoding: unicode
  database: bookswap_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bookswap_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: bookswap_production
  pool: 5
  username:
  password:
